CREATE TABLE tb_documento
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_documento   VARCHAR(255)                            NOT NULL,
    descricao        VARCHAR(255)                            NOT NULL,
    data_inclusao    date,
    data_atualizacao date,
    CONSTRAINT pk_tb_documento PRIMARY KEY (id)
);