CREATE TABLE tb_documento (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    tipo_documento VARCHAR(255) NOT NULL,
    descricao VARCHAR(255) NOT NULL,
    data_inclusao DATE,
    data_atualizacao DATE,
    beneficiario_id VARCHAR(255),
    FOREIGN KEY (beneficiario_id) REFERENCES tb_beneficiario (id)
);